version: "3.8"
services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: taskboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    depends_on:
      - db
    ports:
      - "4000:4000"

  client:
    build:
      context: ./client
    depends_on:
      - server
    ports:
      - "3000:3000"
volumes:
  pgdata:
